### ISSUE TITLE
Hardcoded paths to local-sqlite databases in /tmp

### ISSUE THREAD

**Issue by fiddyspence** [Tojaj/createrepo_c#12]
It would be handy to be able to redirect these paths to another location to cope with diskspace etc, or at least respect $TMPDIR

**Comment by Tojaj** [comment]
Is the new behavior sufficient for you [1] or do you want me to add a new cmd option (something like --local-sqlite-dir)?

[1] https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-tmp-dir

**Comment by Tojaj** [comment]
Feel free to reopen
