### ISSUE TITLE
Support different checksum type for RPMs and XML files

### ISSUE THREAD

**Issue by rohanpm** [Tojaj/createrepo_c#31]
In Spacewalk, repos can be configured using a different checksum method for the XML file entries in repomd.xml and the RPM entries in primary.xml.  (Referred to as "checksum type" and "RPM checksum type".)

Currently it's not possible to make createrepo_c generate repos in this way since it only takes a single --checksum argument.

It would be useful if createrepo_c supported setting both checksum types independently so that it can be used to generate repos configured in this way.

**Comment by Tojaj** [comment]
Sounds good. If you prepare a pull request I will merge it. Thanks
